spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # print sql on console
    properties:
      hibernate:
        format_sql: true # sql formatting
        default_batch_fetch_size: 500 # the item number of "in" of sql statement
    open-in-view: false # limit scope of persistent context to transaction range

logging:
  level:
    org.hibernate.type: trace # sql binding value and result print on console